# Pandas
- Dataframe-Special object to store data in tabular form

# Installation

In [2]:
!pip install pandas

In [3]:
import numpy as np
import pandas as pd

In [5]:
np.random.randint(1,100,5)

array([ 1, 54, 41, 81, 18])

In [7]:
#Try to create a data frame
user_data={
           "MarksA":np.random.randint(1,100,5),
           "MarksB":np.random.randint(50,100,5),
           "MarksC":np.random.randint(1,100,5)
          }
print(user_data)

{'MarksA': array([15, 22, 64, 94, 64]), 'MarksB': array([91, 71, 94, 59, 61]), 'MarksC': array([ 4, 18, 22, 18, 67])}


In [8]:
df=pd.DataFrame(user_data)
print(df)

   MarksA  MarksB  MarksC
0      15      91       4
1      22      71      18
2      64      94      22
3      94      59      18
4      64      61      67


In [9]:
#displays data frame in a better manner
df.head()

MarksA  MarksB  MarksC
0      15      91       4
1      22      71      18
2      64      94      22
3      94      59      18
4      64      61      67

In [10]:
#to display only first 3 coloumns
df.head(n=3)

MarksA  MarksB  MarksC
0      15      91       4
1      22      71      18
2      64      94      22

In [11]:
print(df.columns)

Index(['MarksA', 'MarksB', 'MarksC'], dtype='object')


In [12]:
#to store data into float
df=pd.DataFrame(user_data,dtype='float32')
print(df)

   MarksA  MarksB  MarksC
0    15.0    91.0     4.0
1    22.0    71.0    18.0
2    64.0    94.0    22.0
3    94.0    59.0    18.0
4    64.0    61.0    67.0


In [14]:
#create a csv file from data frame
df.to_csv('marks.csv')

In [15]:
my_data=pd.read_csv('marks.csv')
print(my_data)

   Unnamed: 0  MarksA  MarksB  MarksC
0           0    15.0    91.0     4.0
1           1    22.0    71.0    18.0
2           2    64.0    94.0    22.0
3           3    94.0    59.0    18.0
4           4    64.0    61.0    67.0


In [56]:
#Drop a column
my_data=pd.read_csv('marks.csv')
my_data=my_data.drop(columns=['Unnamed: 0'])
print(my_data)

   MarksA  MarksB  MarksC
0    15.0    91.0     4.0
1    22.0    71.0    18.0
2    64.0    94.0    22.0
3    94.0    59.0    18.0
4    64.0    61.0    67.0


In [17]:
my_data.describe()

MarksA     MarksB     MarksC
count   5.000000   5.000000   5.000000
mean   51.800000  75.200000  25.800000
std    32.866396  16.468151  24.024987
min    15.000000  59.000000   4.000000
25%    22.000000  61.000000  18.000000
50%    64.000000  71.000000  18.000000
75%    64.000000  91.000000  22.000000
max    94.000000  94.000000  67.000000

In [18]:
my_data.tail(n=3)

MarksA  MarksB  MarksC
2    64.0    94.0    22.0
3    94.0    59.0    18.0
4    64.0    61.0    67.0

In [19]:
#accesing a row
df.iloc[3]

MarksA    94.0
MarksB    59.0
MarksC    18.0
Name: 3, dtype: float32

In [20]:
#accesing a row & column
df.iloc[3][1]

59.0

In [21]:
df.iloc[3,1]

59.0

In [22]:
col_idx=df.columns.get_loc('MarksB')
df.iloc[3][col_idx]

59.0

In [27]:
col_idx=[df.columns.get_loc('MarksB'),df.columns.get_loc('MarksC')]
print(col_idx)
df.iloc[3][col_idx]

[1, 2]


MarksB    59.0
MarksC    18.0
Name: 3, dtype: float32

In [29]:
df.iloc[:3,col_idx]

MarksB  MarksC
0    91.0     4.0
1    71.0    18.0
2    94.0    22.0

In [30]:
df.iloc[:3,[1,2]]

MarksB  MarksC
0    91.0     4.0
1    71.0    18.0
2    94.0    22.0

In [31]:
#Sort your dataframe
my_data


MarksA  MarksB  MarksC
0    15.0    91.0     4.0
1    22.0    71.0    18.0
2    64.0    94.0    22.0
3    94.0    59.0    18.0
4    64.0    61.0    67.0

In [34]:
my_data.sort_values(by=["MarksA"],ascending=False)

MarksA  MarksB  MarksC
3    94.0    59.0    18.0
2    64.0    94.0    22.0
4    64.0    61.0    67.0
1    22.0    71.0    18.0
0    15.0    91.0     4.0

In [35]:
my_data.sort_values(by=["MarksA"],ascending=True)

MarksA  MarksB  MarksC
0    15.0    91.0     4.0
1    22.0    71.0    18.0
2    64.0    94.0    22.0
4    64.0    61.0    67.0
3    94.0    59.0    18.0

In [38]:
my_data.sort_values(by=["MarksC","MarksA"],ascending=False)
#first priority is given to MarksC

MarksA  MarksB  MarksC
4    64.0    61.0    67.0
2    64.0    94.0    22.0
3    94.0    59.0    18.0
1    22.0    71.0    18.0
0    15.0    91.0     4.0

In [39]:
data_array=my_data.values
#converts daatframe into numpy array

In [43]:
print(data_array)


[[15. 91.  4.]
 [22. 71. 18.]
 [64. 94. 22.]
 [94. 59. 18.]
 [64. 61. 67.]]


In [45]:
print(my_data.shape)
print(type(data_array))

(5, 3)
<class 'numpy.ndarray'>


In [48]:
data_array[0][0]

15.0

In [50]:
# numpy array back into dataframe
new_df=pd.DataFrame(data_array,dtype='int32',columns=["Physics","Chemistry","Maths"])
print(new_df)

   Physics  Chemistry  Maths
0       15         91      4
1       22         71     18
2       64         94     22
3       94         59     18
4       64         61     67


In [53]:
new_df.to_csv("pcm.csv",index=False)
#removes first column so now when we will reload the csv file no need to drop unnamed column

In [55]:
pcm=pd.read_csv('pcm.csv')
print(pcm)

   Physics  Chemistry  Maths
0       15         91      4
1       22         71     18
2       64         94     22
3       94         59     18
4       64         61     67
