# Matrix Multiplication


In [1]:
import numpy as np
X=np.array([[4,5,7],[10,11,13],[56,80,90]])
Y=np.array([[40,50,70],[100,110,130],[560,800,900]])
print(X)
print(Y)

[[ 4  5  7]
 [10 11 13]
 [56 80 90]]
[[ 40  50  70]
 [100 110 130]
 [560 800 900]]


In [2]:
prod=np.dot(X,Y)
print(prod)

[[ 4580  6350  7230]
 [ 8780 12110 13830]
 [60640 83600 95320]]


# ElementWise Multiplication: Hadmard product

In [4]:
X=np.array([[4,5,7],[10,11,13],[56,80,90]])
Y=np.array([[40,50,70],[100,110,130],[560,800,900]])
print(X)
print(Y)
print(X*Y)

[[ 4  5  7]
 [10 11 13]
 [56 80 90]]
[[ 40  50  70]
 [100 110 130]
 [560 800 900]]
[[  160   250   490]
 [ 1000  1210  1690]
 [31360 64000 81000]]


# Norm of a vector

In [6]:
# can be considered as size of a vector
# x=[x1 x2 x3]
# L^p norm= (x1^p + x2^p + x3^p)^(1/p)
# if vector is 0 then its norm=0
# if we multiply a vector by a scalar then norm also gets multiplied by scalar
# L2 norm is also known as Euclidean norm, also denoted by ||x||
# L1 norm is the absolute sum of members of vector
# Linfinity norm-> absolute value of the largest element


In [7]:
x=np.array([-5,3,10])
#by default L2 norm
lp2=np.linalg.norm(x)
print(lp2)

11.575836902790225


In [8]:
x=np.array([-5,3,10])
# L1 norm
lp1=np.linalg.norm(x,ord=1)
print(lp1)

18.0


In [9]:
# Linfinity norm
x=np.array([-5,3,10])
lpinf=np.linalg.norm(x,ord=np.inf)
print(lpinf)

10.0


In [10]:
# Linfinity norm
x=np.array([-15,3,10])
lpinf=np.linalg.norm(x,ord=np.inf)
print(lpinf)

15.0
