# Scalars & Vectors

- Scalar is a single number, denoted by x
- vector is an array  of scalars, visualize it as a column

In [2]:
import numpy as np

In [3]:
x1=np.array([4,5,6])
print(x1)
print(x1.shape)
print(x1[0])

[4 5 6]
(3,)
4


In [4]:
#We will follow this approach to represent vector
x2=np.array([[4],[5],[6]])
print(x2)
print(x2.shape)
print(x2[0])
print(x2[0][0])

[[4]
 [5]
 [6]]
(3, 1)
[4]
4


In [5]:
x=x1.reshape(-1,)
print(x)

[4 5 6]


# Matrices and Tensors

- Matrix is a 2D array of scalars, denoted by X
- Tensor is an array with more than 2 axes, denoted by X

In [6]:
#Here X is a Matrix
X=np.array([[4,5,7],[10,11,13],[56,80,90]])
print(X.shape)
print(X)

(3, 3)
[[ 4  5  7]
 [10 11 13]
 [56 80 90]]


In [7]:
X[1:,:]=2
print(X)

[[4 5 7]
 [2 2 2]
 [2 2 2]]


In [14]:
#Here T is a tensor
T=np.array([[[4,5,7],[10,11,13]],[[56,80,90],[9,8,10]]])
print(T.shape)
print(T)

(2, 2, 3)
[[[ 4  5  7]
  [10 11 13]]

 [[56 80 90]
  [ 9  8 10]]]


# Transpose

In [24]:
#for vector column changes into row
x=np.array([[1],[2],[3],[4]])
print(x.shape)
print(x)
xt=np.transpose(x)
print(xt.shape)
print(xt)

(4, 1)
[[1]
 [2]
 [3]
 [4]]
(1, 4)
[[1 2 3 4]]


In [25]:
x=np.array([[1,2],[3,4]])
print(x)
xt=np.transpose(x)
print(xt)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


# Broadcasting

- You can add a scalar to a vector ,and numpy will add the vector to each element in the vector 
- Similarly can add vector to a matrix and numpy will add the vector to each column of the matrix

In [26]:
l=[1,2,3,4]
print(l)

[1, 2, 3, 4]


In [27]:
l=l+1

TypeError: can only concatenate list (not "int") to list

In [28]:
l=l**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [29]:
# if this list is a numpy array
l=np.array(l)
l=l+1
print(l)

[2 3 4 5]


In [30]:
l=l**2
print(l)

[ 4  9 16 25]


In [31]:
l=np.array([[1,2,3,4],[5,6,7,8]])
print(l)
l=l+1
print(l)


[[1 2 3 4]
 [5 6 7 8]]
[[2 3 4 5]
 [6 7 8 9]]


In [32]:
l=l**2
print(l)

[[ 4  9 16 25]
 [36 49 64 81]]


In [33]:
l=np.sqrt(l)
print(l)

[[2. 3. 4. 5.]
 [6. 7. 8. 9.]]
