In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
print(a.shape)
# 1-D array

(5,)


In [9]:
b=np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)
# 2-D array

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [14]:
print(a[0])
print(b[0][0])

1
1


In [15]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [16]:
print(c[1][1])

5


In [19]:
#Create array of zeros ,array of ones
a=np.zeros((3,3))
print(a)
print(type(a))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [20]:
b=np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
#array of constants
c=np.full((3,2),5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [23]:
#Identity matrix
d=np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
#Random Matrix
randomMatrix=np.random.random((2,3))
print(randomMatrix)

[[0.30605429 0.63243466 0.36417681]
 [0.28529869 0.83192438 0.44767851]]


In [27]:
print(randomMatrix[1][1])

0.8319243806020691


In [29]:
print(randomMatrix[:,1])

[0.63243466 0.83192438]


In [30]:
print(randomMatrix[:,2])

[0.36417681 0.44767851]


In [31]:
randomMatrix[1,1:]=1
print(randomMatrix)

[[0.30605429 0.63243466 0.36417681]
 [0.28529869 1.         1.        ]]


In [32]:
## Set some rows and columns with any values
z=np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
z[1,:]=5
z[:,-1]=7
print(z)


[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [34]:
#Datatypes
print(z.dtype)
#by default float

float64


In [35]:
m=z=np.zeros((3,3),dtype=np.int64)
print(m)
print(m.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int64


In [39]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

print(x+y)
print(np.add(x,y))

print(x-y)
print(np.subtract(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [41]:
print(x*y)
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))


[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [42]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [44]:
#Matrix Multiplication/Dot Products
print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [45]:
#Multiplication(Dot Product) of vectors-Gives scalar
a=np.array([1,2,3,4])
b=[1,2,3,4]
print(a.dot(b))

30


In [46]:
print(a)

print(sum(a))

[1 2 3 4]
10


In [47]:
print(x)

[[1 2]
 [3 4]]


In [48]:
print(np.sum(x))
# sum along column
print(np.sum(x,axis=0))
#sum along row
print(np.sum(x,axis=1))

10
[4 6]
[3 7]


In [54]:
#Satcking of arrays
print(a)
b=np.array([4,5,6,7])
print(b)


[1 2 3 4]
[4 5 6 7]


In [63]:
a=np.array([1,2,3,4])
np.stack((a,b),axis=0)

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [64]:
np.stack((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

In [68]:
#Reshape a numpy array
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [69]:
a=a.reshape(4,2)
print(a)
print(a.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [70]:
a=a.reshape(8,1)
print(a)
print(a.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(8, 1)


In [71]:
a=a.reshape(8,)
print(a)
print(a.shape)
#linear array

[1 2 3 4 5 6 7 8]
(8,)


In [73]:
# if we do not want to calculate rows or column for reshaping write -1, it will find automatically
a=a.reshape(4,-1)
print(a)
print(a.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [74]:
a=a.reshape(-1,4)
print(a)
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
