# Numpy Random Module

    rand : Random values in a given shape.
    randn : Return a sample (or samples) from the “standard normal” distribution.
    randint : Return random integers from low (inclusive) to high (exclusive).
    random : Return random floats in the half-open interval [0.0, 1.0)
    choice : Generates a random sample from a given 1-D array
    Shuffle : Shuffles the contents of a sequence



In [3]:
import numpy as np

In [4]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
b=np.arange(10)+5
print(b)

[ 5  6  7  8  9 10 11 12 13 14]


In [6]:
np.random.shuffle(a)
print(a)

[8 9 6 5 0 4 7 2 1 3]


In [7]:
np.random.shuffle(a)
print(a)

[6 7 0 2 1 5 9 4 3 8]


In [8]:
np.random.shuffle(a)
print(a)

[3 1 9 6 8 0 5 4 2 7]


In [9]:
a=np.random.rand(2,3)
print(a)

[[0.05281297 0.47670298 0.76294173]
 [0.45475724 0.55221929 0.0402074 ]]


In [10]:
#returns values from a Standard Normal Distribution
a=np.random.randn(2,3)
print(a)

[[-0.27982068  0.10078449 -0.89980225]
 [ 0.54212939 -0.41191473 -1.27242497]]


In [11]:
a=np.random.randint(1,100,5)
print(a)

[95 30 12 37 24]


In [13]:
#Randomly pick one element from array
element=np.random.choice([1,2,3,4,5,6,7,8])
print(element)

5


In [14]:
element=np.random.choice([1,2,3,4,5,6,7,8])
print(element)

2


In [39]:
#if we want to generate our random numbers in the same order everytime  we use seed function
np.random.seed(1)
element=np.random.choice([1,2,3,4,5,6,7,8])
print(element)

6


In [38]:
np.random.seed(1)
element=np.random.choice([1,2,3,4,5,6,7,8])
print(element)

6
