
Some More Numpy Functions - Statistics

    -min,max
    -mean
    -median
    -average
    -variance
    -standard devidation



In [4]:
import numpy as np

In [6]:
a=np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
#Specify axis for the direction in case of multidimensional array
print(np.min(a,axis=0))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]


In [7]:
print(np.min(a,axis=1))

[1 0]


In [9]:
#mean->average of all elements
b=np.array([1,2,3,4,5])
m=sum(b)/5
print(m)
print(np.mean(b))

3.0
3.0


In [12]:
a=np.array([[1,2,3,4],[7,6,2,0]])
print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [13]:
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))


[4.  4.  2.5 2. ]
[2.5  3.75]


In [15]:
c=np.array([1,5,4,2,0])
print(np.median(c))

2.0


In [16]:
#Mean vs Average(weighted)
print(np.mean(c))

2.4


In [18]:
#Average
wt=np.array([1,2,3,4,5])
print(np.average(c,weights=wt))

2.066666666666667


In [19]:
#if weigths =1 ,then mean =avg
wt=np.array([1,1,1,1,1])
print(np.average(c,weights=wt))

2.4


In [20]:
#Standard deviation
u=np.mean(c)
myStd=np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

1.854723699099141


In [22]:
dev=np.std(c)
print(dev)

1.854723699099141


In [24]:
#variance
print(myStd**2)
print(np.var(c))

3.440000000000001
3.4400000000000004
